### ISSUE TITLE
Lightstone does not work with Minecraft Beta 1.5

### ISSUE THREAD

**Issue by zhuowei** [grahamedgecombe/lightstone#18]
The beta 1.5 protocol switched to UTF-16 strings, breaking the codecs.

**Comment by grahamedgecombe** [comment]
I've fixed the strings and the identification message but I'm not sure if there is anything else.

This is the output of a tool I use for helping with packets: https://gist.github.com/5597f584fbfd50778cc9. A few things are wrong (most notably packets which have a for loop in them: the data type is not repeated) but it should help as a general guide for seeing if any other packets need changing.

**Comment by grahamedgecombe** [comment]
Forgot to close this when I dealt with the UTF-16 strings last time.
