### ISSUE TITLE
TaskScheduler does not pulse

### ISSUE THREAD

**Issue by zhuowei** [grahamedgecombe/lightstone#2]
When the server runs, it accepts connections but will not respond to packets. Commenting out server.getWorld().pulse() in TaskScheduler fixes it.

**Comment by grahamedgecombe** [comment]
I've fixed this (there were a few thread safety issues) but will have to push when I get home due to a restrictive firewall.

**Comment by grahamedgecombe** [comment]
Closed by 9d8f8b5756acdf933048ebfc4dc11960640e17a3: several parts of the code called from the task scheduler and Netty&#39;s event handler were not thread safe.
