### ISSUE TITLE
Full support for protocol version 10

### ISSUE THREAD

**Issue by grahamedgecombe** [grahamedgecombe/lightstone#7]
The following packets need to be implemented to support protocol version 10:
- 0x11 (use bed?)
- 0x1B
- 0x46 (invalid bed?)

**Comment by grahamedgecombe** [comment]
Merged pull request #10 which added support for packet 0x11.

**Comment by zhuowei** [comment]
It was actually packet 0x11 (Use bed).

**Comment by grahamedgecombe** [comment]
Merged pull request #19 which contains 0x1B, 0x46 and a load of others too, so I think we're up to date with all the codecs/messages again.
