### ISSUE TITLE
Multi-dimension support

### ISSUE THREAD

**Issue by grahamedgecombe** [grahamedgecombe/lightstone#8]
I think the best way to handle this is to create a new class, called dimension. Each world will consist of multiple dimensions. Every entity will have a reference to the dimension it is in (instead of the world), and each dimension would then have a reference to the world it belongs to. Then, things just need to be split up between the dimension and world classes and a little bit of extra code to determine the default dimension when the player joins the server and that sort of thing.

I'm not sure whether dimensions should have different ChunkIoServices or not. I'm think ChunkIoService per world is probably the best thing, as files like session.lock and level.dat are shared between all dimensions. Each dimension, however, would need a different WorldGenerator.

**Comment by ppvolto** [comment]
For the WorldGenerator is a Interface with GeneratorLookupService most usable to Change Region Settings from Chunk to Chunk, Dimension to Dimension or World to World. For each Dimension to set one level.dat with the specification of the Dimension and a MCRegion file prefixes.

**Comment by grahamedgecombe** [comment]
Pull request #21 should take care of this, so I'm closing this issue and any further discussion about the impl can take place there.
